### ISSUE TITLE
Running List of Main Objectives

### ISSUE THREAD

**Issue by maxtitcomb** [mlap/neon4cast-aquatics#12]
Deadlines: 
- Thursday, April 22nd: Have all 3 drafts of our individual forecasts prepared to share. 
- Thursday, April 29th: Have final draft completed and ready to go.
- May 3-15th (dead week & finals week): Finalize forecasting model. Prepare for final submission. 
- May 15-31st: Input April data released on May 15th to make forecast for weeks of _May 1-8th_ 

**Forecast submissions will due beginning May 31, 2021 at 11:59 Eastern Standard Time (UTC−05:00) for forecasts that start May 1. Final forecast submissions will be due on August 31, 2021 at 11:59 Eastern Standard Time (UTC−05:00) for forecasts that start August 1.**

General:
- [x] Read through [Modeling ](https://github.com/mlap/neon4cast-aquatics/issues/8) issue tab to view classes of models we could use. Learn about different classes of models we could use: [Bayesian models](https://bookdown.org/marklhc/notes_bookdown/introduction.html) (CH 1,2,4,6), neural networks, [Machine Learning (ML) ](https://otexts.com/fpp3/nnetar.html)Models, etc. **Thursday we will go over Bayesian modeling on 3/8/2021 with Marcus. Maybe one month of Machine Learning & one month of Bayesian.**
- [ ] Use literature examples of forecasting to try out models with different approaches. 
- [x] Figure out set up of sensors for Barco site: number, fixed/floating position, etc. 

Lin:
- [ ] Was going to look into grading process for the model 

Max:
- [x] Finish setting up thelio & cloning repository
- [x] Learn more about Neural networks and Bayesian models (monte carlo specifically)
- [ ] Plot relationships between drivers & include alongside plots showing [Time vs. Drivers](https://github.com/mlap/neon4cast-aquatics/issues/10)
- [ ] Create base forecasting model in R to build on and test out grading with. (Variables: diffusion, photosynthesis, respiration, mortality, and others)
- [ ] Use [Fable](https://fable.tidyverts.org/reference/index.html) R Package to do basic forecasting analysis. Main package site is [here](https://fable.tidyverts.org/index.html)

Main links of project requirements and deadlines:
- [ ] [EFI RCN NEON Ecological Forecast Challenge](https://ecoforecast.org/efi-rcn-forecast-challenges/)
- [ ] [NEON Aquatics Forecasting Challenge_Targets and Other Environmental Variables](https://docs.google.com/document/d/1SXWrYcIGqcWlh6-BLuywL_ISl4PBSFHUHjnz_sbwLQg/edit#heading=h.kpl6ram3svtr)

A list of some useful links I previously posted:
- [ ] [Details of the targets, how they are calculated, descriptions of the target files, and examples of other environmental variables that could be used](https://docs.google.com/document/d/1SXWrYcIGqcWlh6-BLuywL_ISl4PBSFHUHjnz_sbwLQg/edit?usp=sharing)
- [ ] Detailed Information on site: [Barco Lake](https://www.neonscience.org/field-sites/barc)
- [ ] Download raw data [here](https://data.neonscience.org/data-products/explore)
- [ ] Spatial data: [here](https://www.neonscience.org/data-samples/data/spatial-data-maps) & [here](https://neon.maps.arcgis.com/home/index.html)
- [ ] [General info on our study site from Sarah](https://github.com/mlap/neon4cast-aquatics/issues/2#issuecomment-768611278)
